version: '3.3'

services:
  db:
    image: postgis/postgis:13-3.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge