version: '3.3'

services:
  db:
    image: postgis/postgis:13-3.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge