name: Django CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libsqlite3-mod-spatialite
        sudo apt-get install -y software-properties-common &&\
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable &&\
        sudo apt-get update &&\
        sudo apt-get install -y libgdal-dev gdal-bin
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
    - name: Setting up DB container
      run: |
        docker-compose up -d
    - name: Run Tests
      run: |
        python manage.py test